definitions:
  response.DocResponse:
    properties:
      code:
        type: integer
      message:
        type: string
      result: {}
      status:
        $ref: '#/definitions/response.Status'
    type: object
  response.Status:
    enum:
    - success
    - error
    - warning
    type: string
    x-enum-varnames:
    - StatusSuccess
    - StatusError
    - StatusWarning
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Handles user authentication.
      parameters:
      - description: Email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.DocResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.DocResponse'
      summary: Handle authentication login
      tags:
      - auth
  /auth/registration:
    post:
      consumes:
      - application/json
      description: Handles user authentication.
      parameters:
      - description: Email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: Confirm Password
        in: body
        name: confirm_password
        required: true
        schema:
          type: string
      - description: Name
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: Surname
        in: body
        name: surname
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.DocResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.DocResponse'
      summary: Handle authentication login
      tags:
      - auth
swagger: "2.0"
