#!/usr/bin/env sh

if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor|perf|build|revert)(\(.+?\))?: .{1,}$"; then
    echo "$(tput setaf 1)Aborting commit. Your commit message is invalid.$(tput sgr 0)" >&2
    exit 1
fi
